# This is a basic workflow to help you get started with Actions

name: Terrascan 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terrascan_job_terraform:
    runs-on: ubuntu-latest
    name: terrascan-action-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        iac_dir: Templates/
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
 
  # checkov_terrafrom_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.8
  #     - name: Test with Checkov
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@master
  #       with:
  #         directory: 'Templates/'
  #         framework: terraform  # Kan niet 2 frameworks tegelijk gebruiken
  #     - name: Upload Checkov Terraform results
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: results.sarif        
  
  # checkov_cloudformation_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.8
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.8
  #     - name: Test with Checkov
  #       id: checkov
  #       uses: bridgecrewio/checkov-action@master
  #       with:
  #         directory: 'cloudformation/'
  #         framework: cloudformation  
  #     - name: Upload Checkov CloudFormation SARIF results
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: results.sarif

  # kics_job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run KICS
  #       id: kics
  #       uses: Checkmarx/kics-github-action@v2.1.0
  #       with: 
  #         path: "Templates/, cloudformation/" 
  #         platform_type: "terraform, cloudformation"
  #         fail_on: "critical"
  #     - name: Upload KICS SARIF results
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: results.sarif
