# This is a basic workflow to help you get started with Actions

name: IaC Scanners

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_dir: 'Terraform/'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
        
 
  checkov_terrafrom_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: Terraform/
          framework: terraform
          output_format: 'sarif'
          output_file_path: 'checkov_terraform.sarif'
      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: checkov_terraform.sarif
          
  checkov_cloudformation_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: CloudFormation/
          framework: cloudformation
          output_format: 'sarif'
          output_file_path: 'checkov_cloudformation.sarif'
      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: checkov_cloudformation.sarif  

  kics_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: Run KICS
        id: kics
        uses: Checkmarx/kics-github-action@v2.1.0
        with: 
          path: "Terraform/, CloudFormation/" 
          fail_on: "critical"
          ignore_on_exit: results
          output_path: results-dir
          platform_type: "terraform, cloudformation"
          output_formats: "json,sarif"
          exclude_paths: "terraform/gcp/big_data.tf,terraform/azure"
          exclude_queries: "0437633b-daa6-4bbc-8526-c0d2443b946e"
      - name: show results
        run: |
          cat results-dir/results.json
          cat results-dir/results.sarif

      - name: Upload KICS SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results-dir/results.sarif
